package com.fyc.park.bean;

public class Mapliceandposition {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapliceandposition.PositionNum
	 * @mbggenerated
	 */
	private Integer positionnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapliceandposition.CarLicense
	 * @mbggenerated
	 */
	private String carlicense;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapliceandposition.CarPicPath
	 * @mbggenerated
	 */
	private String carpicpath;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapliceandposition.PositionNum
	 * @return  the value of mapliceandposition.PositionNum
	 * @mbggenerated
	 */
	public Integer getPositionnum() {
		return positionnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapliceandposition.PositionNum
	 * @param positionnum  the value for mapliceandposition.PositionNum
	 * @mbggenerated
	 */
	public void setPositionnum(Integer positionnum) {
		this.positionnum = positionnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapliceandposition.CarLicense
	 * @return  the value of mapliceandposition.CarLicense
	 * @mbggenerated
	 */
	public String getCarlicense() {
		return carlicense;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapliceandposition.CarLicense
	 * @param carlicense  the value for mapliceandposition.CarLicense
	 * @mbggenerated
	 */
	public void setCarlicense(String carlicense) {
		this.carlicense = carlicense == null ? null : carlicense.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapliceandposition.CarPicPath
	 * @return  the value of mapliceandposition.CarPicPath
	 * @mbggenerated
	 */
	public String getCarpicpath() {
		return carpicpath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapliceandposition.CarPicPath
	 * @param carpicpath  the value for mapliceandposition.CarPicPath
	 * @mbggenerated
	 */
	public void setCarpicpath(String carpicpath) {
		this.carpicpath = carpicpath == null ? null : carpicpath.trim();
	}
}