package com.fyc.park.bean;

import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.fyc.park.bean.Mapliceandposition;

public interface MapliceandpositionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapliceandposition
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer positionnum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapliceandposition
	 * @mbggenerated
	 */
	int insert(Mapliceandposition record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapliceandposition
	 * @mbggenerated
	 */
	Mapliceandposition selectByPrimaryKey(Integer positionnum);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapliceandposition
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Mapliceandposition record);

	Map<?,?> getSlotInfo(@Param("carLicense")String carLicense, @Param("queryPlace")int queryPlace);
}