package com.fyc.park.bean;

import com.fyc.park.bean.Mappositionandquerypic;

public interface MappositionandquerypicMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mappositionandquerypic
	 * @mbggenerated
	 */
	int insert(Mappositionandquerypic record);
}