package com.fyc.park.bean;

public class Mappositionandquerypic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mappositionandquerypic.PositionNum
     *
     * @mbggenerated
     */
    private Integer positionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mappositionandquerypic.QueryPlace
     *
     * @mbggenerated
     */
    private Integer queryplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mappositionandquerypic.RoadPicPath
     *
     * @mbggenerated
     */
    private String roadpicpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mappositionandquerypic.PositionNum
     *
     * @return the value of mappositionandquerypic.PositionNum
     *
     * @mbggenerated
     */
    public Integer getPositionnum() {
        return positionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mappositionandquerypic.PositionNum
     *
     * @param positionnum the value for mappositionandquerypic.PositionNum
     *
     * @mbggenerated
     */
    public void setPositionnum(Integer positionnum) {
        this.positionnum = positionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mappositionandquerypic.QueryPlace
     *
     * @return the value of mappositionandquerypic.QueryPlace
     *
     * @mbggenerated
     */
    public Integer getQueryplace() {
        return queryplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mappositionandquerypic.QueryPlace
     *
     * @param queryplace the value for mappositionandquerypic.QueryPlace
     *
     * @mbggenerated
     */
    public void setQueryplace(Integer queryplace) {
        this.queryplace = queryplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mappositionandquerypic.RoadPicPath
     *
     * @return the value of mappositionandquerypic.RoadPicPath
     *
     * @mbggenerated
     */
    public String getRoadpicpath() {
        return roadpicpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mappositionandquerypic.RoadPicPath
     *
     * @param roadpicpath the value for mappositionandquerypic.RoadPicPath
     *
     * @mbggenerated
     */
    public void setRoadpicpath(String roadpicpath) {
        this.roadpicpath = roadpicpath == null ? null : roadpicpath.trim();
    }
}