package com.fyc.park.bean;

public class Mod {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mod.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mod.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mod.url
	 * @mbggenerated
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mod.routerId
	 * @mbggenerated
	 */
	private String routerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mod.parentId
	 * @mbggenerated
	 */
	private Integer parentid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mod.id
	 * @return  the value of t_mod.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mod.id
	 * @param id  the value for t_mod.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mod.name
	 * @return  the value of t_mod.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mod.name
	 * @param name  the value for t_mod.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mod.url
	 * @return  the value of t_mod.url
	 * @mbggenerated
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mod.url
	 * @param url  the value for t_mod.url
	 * @mbggenerated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mod.routerId
	 * @return  the value of t_mod.routerId
	 * @mbggenerated
	 */
	public String getRouterid() {
		return routerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mod.routerId
	 * @param routerid  the value for t_mod.routerId
	 * @mbggenerated
	 */
	public void setRouterid(String routerid) {
		this.routerid = routerid == null ? null : routerid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mod.parentId
	 * @return  the value of t_mod.parentId
	 * @mbggenerated
	 */
	public Integer getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mod.parentId
	 * @param parentid  the value for t_mod.parentId
	 * @mbggenerated
	 */
	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}
}