package com.fyc.park.bean;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.fyc.park.bean.Mod;

public interface ModMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mod
	 * @mbggenerated
	 */
	int deleteModByKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mod
	 * @mbggenerated
	 */
	int insert(Mod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mod
	 * @mbggenerated
	 */
	Mod selectModByKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mod
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Mod record);
	
	List<Mod> getUserMods(@Param("userId") Integer userId);
}