package com.fyc.park.bean;

public class Role {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_role.name
	 * @mbggenerated
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.id
	 * @return  the value of t_role.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.id
	 * @param id  the value for t_role.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_role.name
	 * @return  the value of t_role.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_role.name
	 * @param name  the value for t_role.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}
}