package com.fyc.park.bean;

import com.fyc.park.bean.Rolemod;

public interface RolemodMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_rolemod
	 * @mbggenerated
	 */
	int deleteRolemodByKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_rolemod
	 * @mbggenerated
	 */
	int insert(Rolemod record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_rolemod
	 * @mbggenerated
	 */
	Rolemod selectRolemodByKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_rolemod
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Rolemod record);
}