package com.fyc.park.bean;

public class Rolemod {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_rolemod.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_rolemod.roleId
	 * @mbggenerated
	 */
	private Integer roleid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_rolemod.modId
	 * @mbggenerated
	 */
	private Integer modid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_rolemod.id
	 * @return  the value of t_rolemod.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_rolemod.id
	 * @param id  the value for t_rolemod.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_rolemod.roleId
	 * @return  the value of t_rolemod.roleId
	 * @mbggenerated
	 */
	public Integer getRoleid() {
		return roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_rolemod.roleId
	 * @param roleid  the value for t_rolemod.roleId
	 * @mbggenerated
	 */
	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_rolemod.modId
	 * @return  the value of t_rolemod.modId
	 * @mbggenerated
	 */
	public Integer getModid() {
		return modid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_rolemod.modId
	 * @param modid  the value for t_rolemod.modId
	 * @mbggenerated
	 */
	public void setModid(Integer modid) {
		this.modid = modid;
	}
}