package com.fyc.park.bean;

import com.fyc.park.bean.Role;

public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	int deleteRoleByKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	Role selectRoleByKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_role
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Role record);
}