package com.fyc.park.bean;

import com.fyc.park.bean.Userrole;

public interface UserroleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_userrole
	 * @mbggenerated
	 */
	int deleteUserroleByKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_userrole
	 * @mbggenerated
	 */
	int insert(Userrole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_userrole
	 * @mbggenerated
	 */
	Userrole selectUserroleByKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_userrole
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Userrole record);
}