package com.fyc.park.bean;


public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.pwd
	 * @mbggenerated
	 */
	private String pwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.mail
	 * @mbggenerated
	 */
	private String mail;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.name
	 * @return  the value of t_user.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.name
	 * @param name  the value for t_user.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.pwd
	 * @return  the value of t_user.pwd
	 * @mbggenerated
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.pwd
	 * @param pwd  the value for t_user.pwd
	 * @mbggenerated
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd == null ? null : pwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.mail
	 * @return  the value of t_user.mail
	 * @mbggenerated
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.mail
	 * @param mail  the value for t_user.mail
	 * @mbggenerated
	 */
	public void setMail(String mail) {
		this.mail = mail == null ? null : mail.trim();
	}
	
}